=== AlexanderMikhel/Music-Manager-1/data/xml/library.dtd
<?xml version="1.0" encoding="UTF-8" ?>
        <!ELEMENT track (genre)>
        <!ELEMENT library (track*)>
        <!ELEMENT genre EMPTY>

        <!ATTLIST track
                trackName CDATA #REQUIRED
                trackArtist CDATA #REQUIRED
                trackAlbum CDATA #REQUIRED
                trackLength CDATA #REQUIRED>
        <!ATTLIST library
                >
        <!ATTLIST genre
                genreName CDATA #REQUIRED
                establishingCentury CDATA #REQUIRED
                >

=== AlexanderMikhel/Music-Manager-1/data/xml/tracks.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE library SYSTEM "library.dtd">
<library>
    <track trackAlbum="Come Fly With Me" trackArtist="Frank Sinatra" trackLength="199" trackName="Come Fly With Me">
        <genre establishingCentury="20" genreName="Jazz"/>
    </track>
    <track trackAlbum="Nice 'N' Easy" trackArtist="Frank Sinatra" trackLength="214" trackName="Nice 'N' Easy">
        <genre establishingCentury="20" genreName="Jazz"/>
    </track>
    <track trackAlbum="Nice 'N' Easy" trackArtist="Frank Sinatra" trackLength="214" trackName="That Old Feeling">
        <genre establishingCentury="20" genreName="Jazz"/>
    </track>
    <track trackAlbum="Everything You've Come To Expect" trackArtist="The Last Shadow Puppets" trackLength="224"
           trackName="Aviation">
        <genre establishingCentury="20" genreName="Alternative"/>
    </track>
    <track trackAlbum="Yours, Dreamily" trackArtist="The Arcs" trackLength="199" trackName="Stay in My Corner">
        <genre establishingCentury="20" genreName="Alternative"/>
    </track>
    <track trackAlbum="Seventh Star" trackArtist="Black Sabbath" trackLength="269" trackName="No Stranger to Love">
        <genre establishingCentury="20" genreName="Heavy Metal"/>
    </track>
    <track trackAlbum="Love" trackArtist="The Cult" trackLength="263" trackName="She Sells Sanctuary">
        <genre establishingCentury="20" genreName="Alternative"/>
    </track>
    <track trackAlbum="French Style" trackArtist="Dean Martin" trackLength="216" trackName="April In Paris">
        <genre establishingCentury="18" genreName="Vocal"/>
    </track>
    <track trackAlbum="L.A. Woman" trackArtist="The Doors" trackLength="470" trackName="L.A. Woman">
        <genre establishingCentury="20" genreName="Rock"/>
    </track>
    <track trackAlbum="Ain't No Love In the Heart of the City" trackArtist="Bobby Bland" trackLength="156"
           trackName="Two Steps from the Blues">
        <genre establishingCentury="20" genreName="Blues"/>
    </track>
    <track trackAlbum="Blues of Desperation" trackArtist="Joe Bonamassa" trackLength="347" trackName="Drive">
        <genre establishingCentury="Blues" genreName="20"/>
    </track>
    <track trackAlbum="Hard Again" trackArtist="Muddy Waters" trackLength="215"
           trackName="The Blues Had a Baby and They Named It Rock and Roll">
        <genre establishingCentury="20" genreName="Blues"/>
    </track>
    <track trackAlbum="Innosents" trackArtist="Moby" trackLength="280" trackName="The Last Day">
        <genre establishingCentury="21" genreName="Electronic"/>
    </track>
    <track trackAlbum="Retrograde" trackArtist="James Blake" trackLength="224" trackName="Retrograde">
        <genre establishingCentury="21" genreName="Electronic"/>
    </track>
    <track trackAlbum="Innosents" trackArtist="Moby" trackLength="360" trackName="Almost Home">
        <genre establishingCentury="21" genreName="Electronic"/>
    </track>
    <track trackAlbum="El Camino" trackArtist="The Black Keys" trackLength="224" trackName="Gold on the Celling">
        <genre establishingCentury="20" genreName="Rock"/>
    </track>
</library>

=== AlexanderMikhel/Music-Manager-1/data/xml/trackStore.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE library SYSTEM "library.dtd">
<library>
    <track trackAlbum="Come Fly With Me" trackArtist="Frank Sinatra" trackGenre="Jazz" trackLength="199" trackName="Come Fly With Me"/>
    <track trackAlbum="Nice 'N' Easy" trackArtist="Frank Sinatra" trackGenre="Jazz" trackLength="214" trackName="Nice 'N' Easy"/>
    <track trackAlbum="Nice 'N' Easy" trackArtist="Frank Sinatra" trackGenre="Jazz" trackLength="214" trackName="That Old Feeling"/>
    <track trackAlbum="Everything You've Come To Expect" trackArtist="The Last Shadow Puppets" trackGenre="Alternative" trackLength="224" trackName="Aviation"/>
    <track trackAlbum="Yours, Dreamily" trackArtist="The Arcs" trackGenre="Alternative" trackLength="199" trackName="Stay in My Corner"/>
    <track trackAlbum="Seventh Star" trackArtist="Black Sabbath" trackGenre="Heavy Metal" trackLength="269" trackName="No Stranger to Love"/>
    <track trackAlbum="Love" trackArtist="The Cult" trackGenre="Alternative" trackLength="263" trackName="She Sells Sanctuary"/>
    <track trackAlbum="French Style" trackArtist="Dean Martin" trackGenre="Vocal" trackLength="216" trackName="April In Paris"/>
    <track trackAlbum="L.A. Woman" trackArtist="The Doors" trackGenre="Rock" trackLength="470" trackName="L.A. Woman"/>
    <track trackAlbum="Ain't No Love In the Heart of the City" trackArtist="Bobby Bland" trackGenre="Blues" trackLength="156" trackName="Two Steps from the Blues"/>
    <track trackAlbum="Blues of Desperation" trackArtist="Joe Bonamassa" trackGenre="Blues" trackLength="347" trackName="Drive"/>
    <track trackAlbum="Hard Again" trackArtist="Muddy Waters" trackGenre="Blues" trackLength="215" trackName="The Blues Had a Baby and They Named It Rock and Roll"/>
    <track trackAlbum="Innocents" trackArtist="Moby" trackGenre="Electronic" trackLength="280" trackName="The Last Day"/>
    <track trackAlbum="Retrograde" trackArtist="James Blake" trackGenre="Electronic" trackLength="224" trackName="Retrograde"/>
    <track trackAlbum="Innocents" trackArtist="Moby" trackGenre="Electronic" trackLength="360" trackName="Almost Home"/>
    <track trackAlbum="El Camino" trackArtist="The Black Keys" trackGenre="Rock" trackLength="224" trackName="Gold on the Celling"/>


    <genre establishingCentury="20" genreName="Blues"/>
    <genre establishingCentury="20" genreName="Jazz"/>
    <genre establishingCentury="20" genreName="Rock"/>
    <genre establishingCentury="20" genreName="Electronic"/>
    <genre establishingCentury="18" genreName="Vocal"/>
    <genre establishingCentury="21" genreName="Alternative"/>
    <genre establishingCentury="20" genreName="Heavy Metal"/>
</library>
